default:
  properties:
    webdriver.defaultTimeout: 10
    page.title.timeout: 30
    thread.count: 3
    webdriver.cap.recordVideo: false
    webdriver.cap.maxInstances: 1
    allure.report: true
    allure.create.enviroment: true   
    timings.implicitTimeout: 500000
  contexts: [chrome]
  
